name: GitHub Actions Demo
on:
  push:
    branches:
      - test-branch-master-must-follow
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: push branch to master
        run: |
          git fetch origin
          git push -f origin test-branch-master-must-follow:master
